language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests tests -v --with-coverage --cover-package=api
after_success:
  - coveralls